version: '2.4'
services:
  squid:
    build: 
      context: .
      dockerfile: alpine.Dockerfile
    network_mode: "host"
    #ports:
    # - "9191:9191"
    environment:
      - PASSWORD=pass
      - PORT=9191
     